spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.199.128:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

server:
  port: 8080
  servlet:
    context-path: /sell
#使用logBack-spring.xml 文件配置代替
#logging:
#  pattern:
#    console: "%d -%msg%n"
#  #path: D:\WorkSpaces\InteliJ IDE-Workspace\sell
#  file: D:\WorkSpaces\InteliJ IDE-Workspace\sell\log\sell.log
#  level:
#     com.sell.LoggerTest: debug


